name: Lint, Test, Prettier

on:
  push:
    branches: [astria]
  pull_request:
    branches: [astria]

jobs:
  server-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Generate
        run: go generate -x

      - name: Build
        run: go build -v

      - name: Test
        run: go test -v ./...

  server-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  web-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - run: npm install
        working-directory: web

      - run: npm run prettier --check 'src/**/*.{css,html,js,svelte}'
        working-directory: web
